### ISSUE TITLE
restrictedSrcAddressApp required but missing in failover example yaml files

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates-v2#10]
## Describe the bug
 
The parameter 'restrictedSrcAddressApp' is set to be required 'yes' but it is not listed in the example yaml files. As a result, if user uses example failover yaml file, it is missing the parameter. The deployment will fail in google when python template tries to read the value.
 
## Expected behavior
 
User should be able to pull down example yaml file that indicates all required and/or optional values. This way user is forced to enter values into yaml that are required and missing.
 
## Current behavior
 
Parameter is required, but it is missing from example yaml. GCP deployment fails with an error that the parameter and value is basically missing.

## Possible solution
 
Make sure that the restrictedSrcAddressApp parameter is in the example yaml files as required for all templates. For reference, this is found in the Quickstart yaml example files but not failover. I did not check other templates.

Add this to the 'sample_failover_existing_network.yaml' for example...
```
      # restrictedSrcAddressApp:*
      # 0.0.0.0/0**
      restrictedSrcAddressApp:
```
 
## Steps to reproduce
 
1. clone repo, update yaml file, update runtime init file
2. launch bigip deployment
3. fails with missing parameter
 
## Screenshots
 
n/a
 
## Context
 
n/a
 
## Your Environment

n/a

**Comment by shyawnkarim** [comment]
Thanks for reporting this. I've added it to our backlog and it is being tracked with internal ID, ESECLDTPLT-3137.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 2.4.0.0](https://github.com/F5Networks/f5-google-gdm-templates-v2/releases/tag/v2.4.0.0).

**Comment by JeffGiroux** [comment]
This is not fixed. The yaml file in failover existing is still missing the required parameter.

https://github.com/F5Networks/f5-google-gdm-templates-v2/blob/main/examples/failover/sample_failover_existing_network.yaml

**Comment by shyawnkarim** [comment]
Thanks for letting me know. This was improperly marked done and is still open in our backlog.

**Comment by shyawnkarim** [comment]
Thanks for letting me know. This was improperly marked done and is still open in our backlog.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved (for real this time) with [Release 2.5.0.0](https://github.com/F5Networks/f5-google-gdm-templates-v2/releases/tag/v2.5.0.0).
